@host = http://localhost:5000

###
# Publish post
POST {{host}}/posts
Content-Type: application/json

{
	"username": "bruno",
	"password": "brunao",
	"categoriesIds": [
		1,4
	]
}

###
# Show timeline
GET {{host}}/posts?username=bruno&password=brunao
Content-Type: application/json

{
}

###
# List users
POST {{host}}/users 
Content-Type: application/json

{
	"username": "bruno",
	"password": "brunao"
}