@host = http://localhost:5000

###
# Posts
POST {{host}}/posts
Content-Type: application/json

{
	"username": "bruno",
	"password": "brunao",
	"categoriesIds": [
		1,4
	]
}

###
# Users
POST {{host}}/users 
Content-Type: application/json

{
	"username": "bruno",
	"password": "brunao"
}