@host = http://localhost:5000

###
# Posts
POST {{host}}/posts
Content-Type: application/json

{
	"userId": 1,
	"categoriesIds": [
		1
	]
}

###
# Users
POST {{host}}/users 
Content-Type: application/json

{
	"username": "username14",
	"password": "pwd14"
}